# Generated by Django 4.1 on 2024-03-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_thinking_alter_post_mypost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mypost',
            field=models.BinaryField(null=True),
        ),
    ]
